# version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: helpdesk-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    # env_file: 
    #   - ./.env.docker
    environment: # Variáveis de ambiente com valores explícitos
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: helpdesk_db
      DB_USERNAME: helpdesk_user
      DB_PASSWORD: secret
    depends_on:
      - database
    networks:
      - helpdesk-network

  nginx:
    image: nginx:latest
    container_name: helpdesk-nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - helpdesk-network

  database:
    image: postgres:15-alpine
    container_name: helpdesk-db
    # env_file: ./.env.docker
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - helpdesk-network

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: helpdesk-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - helpdesk-network

volumes:
  db_data:

networks:
  helpdesk-network:
    driver: bridge